version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo Installing frontend dependencies...
      - cd client && npm install
      - echo  Installing backend dependencies...
      - cd .. && cd server && npm install
  build:
    commands:
      - echo Deploying backend...
      - npm start
      - echo Building frontend...
      - cd .. && cd client && npm run build
  post_build:
    commands:
      - echo Deployment completed at 'date'
